export type Variant = {
  id: number;
  name: string;
  sku: string;
  price: number;
  stock: number;
  image: string;
  attributes: Record<string, string>;
  active: boolean;
};
export type Product = {
  id: number;
  name: string;
  slug: string;
  sku: string;
  category: string;
  category_slug: string;
  category_id: number;
  brand: string;
  brand_id: number;
  description: string;
  short_description: string;
  price: number;
  original_price: number;
  cost_price: number;
  low_stock_threshold: number;
  specifications: Record<string, string>;
  features: string[];
  images: string[];
  variants: Variant[];
  stock: number;
  rating: number;
  review_count: number;
  active: boolean;
  featured: boolean;
  seo_title: string;
  seo_description: string;
  created_at: string;
};
export type User = {
  id: number;
  name: string;
  email: string;
  mobile: string;
  role: "ADMIN" | "CUSTOMER";
};
export type CartItem = {
  id: number;
  variant_id: number;
  product_id: number;
  name: string;
  slug: string;
  variant: string;
  sku: string;
  price: number;
  image: string;
  quantity: number;
  stock: number;
};
export type Category = {
  id: number;
  name: string;
  slug: string;
  description: string;
  image: string;
  parent_id: number | null;
  active: boolean;
  seo_title: string;
  seo_description: string;
};
export type Address = {
  id?: number;
  label: string;
  first_name: string;
  last_name: string;
  email: string;
  mobile: string;
  address: string;
  apartment: string;
  city: string;
  state: string;
  pincode: string;
  country: "India";
  is_default: boolean;
};
export type Quote = {
  subtotal: number;
  discount: number;
  shipping: number;
  tax: number;
  total: number;
  coupon: string | null;
};
export type Order = Quote & {
  id: number;
  number: string;
  created_at: string;
  status: string;
  payment_status: string;
  expected_delivery: string;
  shipping_address: Address;
  billing_address: Address;
  delivery: string;
  items: CartItem[];
  customer_name?: string;
  customer_email?: string;
};
export type Settings = {
  store_name: string;
  logo: string;
  email: string;
  phone: string;
  address: string;
  gst: number;
  shipping_charge: number;
  free_shipping_threshold: number;
  express_charge: number;
  cod_enabled: boolean;
  online_enabled: boolean;
};
